### ISSUE TITLE
Survival commands don't exist

### ISSUE THREAD

**Issue by Hanuko33** [infclass/teeworlds-infclassR#91] opened 2023-07-15 09:24 UTC
they just don't exist anywhere, in config, in rcon (f2)...
I buildt it on linux from source with cmake and make.
It just says "command not found"

**Comment by Kaffeine** [comment] 2023-07-15 10:40
Correct. I'm not ready to publish the bots just yet. Maybe I'll publish them eventually (not in the next release though).

**Comment by Kaffeine** [comment] 2023-11-18 22:52
Closed as "Not a bug". Survival rounds are intentionally not available yet.

**Closed as completed by Kaffeine** 2023-11-18 22:52 UTC
Labels: Invalid
